CREATE TABLE `curso_python`.`gran_premio` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NOMBRE` VARCHAR(45) NULL,
  `DISTANCIA` INT NULL,
  `NUM_CARRERAS` INT NULL,
  PRIMARY KEY (`ID`));


CREATE TABLE `curso_python`.`caballos` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NOMBRE` VARCHAR(45) NULL,
  `FECHA_NACIMIENTO` DATETIME NULL,
  `VELOCIDAD` INT NULL,
  `EXPERIENCIA` INT NULL,
  `VALOR_APUESTA` INT NULL,
  PRIMARY KEY (`ID`));


CREATE TABLE `curso_python`.`apostantes` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `NOMBRE` VARCHAR(45) NULL,
  `SALDO` INT NULL,
  PRIMARY KEY (`ID`));


ALTER TABLE `curso_python`.`caballos` 
ADD CONSTRAINT `ID_GRANPREMIO`
  FOREIGN KEY (`ID`)
  REFERENCES `curso_python`.`gran_premio` (`ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

UPDATE `curso_python`.`gran_premio` SET `ID` = '%s', `NOMBRE` = '%s', `DISTANCIA` = '%s', `NUM_CARRERAS` = '%s' WHERE (`ID` = '%s');